<?php
	$arr_states = array('ANDRA PRADESH' => 'Andra Pradesh',
	'ARUNACHAL PRADESH' => 'Arunachal Pradesh',
	'ASSAM' => 'Assam',
	'BIHAR' => 'Bihar',
	'CHHATTISGARH' => 'Chhattisgarh',
	'GOA' => 'Goa',
	'GUJARAT' => 'Gujarat',
	'HARYANA' => 'Haryana',
	'HIMACHAL PRADESH' => 'Himachal Pradesh',
	'JAMMU AND KASHMIR' => 'Jammu and Kashmir',
	'JHARKHAND' => 'Jharkhand',
	'KARNATAKA' => 'Karnataka',
	'KERALA' => 'Kerala',
	'MADYA PRADESH' => 'Madya Pradesh',
	'MAHARASHTRA' => 'Maharashtra',
	'MANIPUR' => 'Manipur',
	'MEGHALAYA' => 'Meghalaya',
	'MIZORAM' => 'Mizoram',
	'NAGALAND' => 'Nagaland',
	'ORISSA' => 'Orissa',
	'PUNJAB' => 'Punjab',
	'RAJASTHAN' => 'Rajasthan',
	'SIKKIM' => 'Sikkim',
	'TAMIL NADU' => 'Tamil Nadu',
	'TRIPURA' => 'Tripura',
	'UTTARANCHAL' => 'Uttaranchal',
	'UTTAR PRADESH' => 'Uttar Pradesh',
	'WEST BENGAL' => 'West Bengal',
	'ANDAMAN AND NICOBAR ISLANDS' => 'Andaman and Nicobar Islands',
	'CHANDIGARH' => 'Chandigarh',
	'DADAR AND NAGAR HAVELI' => 'Dadar and Nagar Haveli',
	'DAMAN AND DIU' => 'Daman and Diu',
	'DELHI' => 'Delhi',
	'LAKSHADEEP' => 'Lakshadeep',
	'PONDICHERRY' => 'Pondicherry');
?>